---
# passwords of virtual machine users
:root_password: katello
:user_password: katello

# your public key(s), usually `cat ~/.ssh/id_rsa.pub`
:authorized_keys: "ssh-rsa somelongblob"

# run virtual machines headless?
:headless: true

:jobs_paths:
- jobs.rb

:commands_paths:
- commands.rb

# additional config file which is deep merged with this one default
:config_overide:

# configuration of a private network for katello machines
:hostonly:
  :name: vboxnet0
  :host_ip: 192.168.25.10
  :dhcp:
    :ip: 192.168.25.1
    :mask: 255.255.255.0
    :lower_ip: 192.168.25.100
    # if you have lot of machines, stretch the boundary
    :upper_ip: 192.168.25.110

:logger:
  :output: "kvizer.log"
  :print_to_stdout: true
  :level: 0

# define which directories to mount on a virtual machine
#   key is name of the directory on VM in user's home (/home/user/redhat)
#   value is path on host, for relative paths root of kvizer is used
:shared_folders:
  :redhat: /path/to/your/repositories/redhat

  # should not be touched
  :remote_bin: ./remote_bin
  :support: ./support

# path to katello on the machine
:katello_path: /home/user/redhat/katello

:virtual_box_version: 4.2.6

# name of the katello base machine
:katello_base: katello-base

# job collections
:base_jobs:
- clean installation
- base
- update
- add-user
- install-guest-additions
- setup-shared-folders
- install-htop
- install-packaging
# note you can use install-katello if nightly is broken, but it can be outdated
- install-katello-nightly
- configure-katello
- turnoff-services
- relax-security
- setup-development
:build_jobs:
- install-packaging
- package2
- reconfigure-katello
- system-test

# default options of jobs
:job_options:
  :package2:
    :source: /home/user/redhat/katello
    :branch: master
    :use_koji: false
